import bcrypt from "bcryptjs";

const data = {
  users: [
    {
      name: "Ariff",
      email: "admin@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: true,
    },
    {
      name: "John",
      email: "user@example.com",
      password: bcrypt.hashSync("123456"),
      isAdmin: false,
    },
  ],

  products: [
    {
      name: "COTTON JACQUARD SHIRT",
      slug: "cotton-jacquard-shirt",
      category: "Shirts",
      image: "../images/cotton-jacquard-shirt.jpg",
      price: 239,
      countInStock: 10,
      brand: "ZARA",
      rating: 4.5,
      numReviews: 10,
      description: "Relaxed fit shirt made of a cotton blend. Featuring a camp collar, short sleeves and a button-up front.",
    },
    {
      name: "EMBROIDERED SHIRT",
      slug: "embroidered-shirt",
      category: "Shirts",
      image: "../images/embroidered-shirt.jpg",
      price: 239,
      countInStock: 5,
      brand: "ZARA",
      rating: 5,
      numReviews: 5,
      description: "Relaxed fit shirt made of cotton. Camp collar and short sleeves. Contrast embroidery all over the garment. Button-up front.",
    },
    {
      name: "FADED CHECK SHIRT",
      slug: "faded-check-shirt",
      category: "Shirts",
      image: "../images/faded-check-shirt.jpg",
      price: 199,
      countInStock: 8,
      brand: "ZARA",
      rating: 3.5,
      numReviews: 7,
      description: "Collared relaxed fit shirt made of cotton. Long sleeves with buttoned cuffs. Chest patch pocket. Faded effect.",
    },
    {
      name: "GEOMETRIC PRINT SHIRT",
      slug: "geometric-print-shirt",
      category: "Shirts",
      image: "../images/geometric-print-shirt.jpg",
      price: 199,
      countInStock: 8,
      brand: "ZARA",
      rating: 3.5,
      numReviews: 7,
      description: "Regular fit shirt with a camp collar, short sleeves and a button-up front.",
    },
    {
      name: "BOXY-FIT TECHNICAL SHIRT",
      slug: "boxy-fit-technical-shirt",
      category: "Shirts",
      image: "../images/boxy-fit-technical-shirt.jpg",
      price: 199,
      countInStock: 8,
      brand: "ZARA",
      rating: 3.5,
      numReviews: 7,
      description: "Boxy-fit shirt made of lightweight technical fabric. Spread collar and short sleeves. Button-up front hidden by a placket.",
    },
    {
      name: "ABSTRACT PRINT SHIRT",
      slug: "abstract-print-shirt",
      category: "Shirts",
      image: "../images/abstract-print-shirt.jpg",
      price: 199,
      countInStock: 8,
      brand: "ZARA",
      rating: 3.5,
      numReviews: 7,
      description: "Relaxed fit shirt in viscose fabric. Camp collar and short sleeves. Split hem. Button-up front.",
    },
    {
      name: "RIPPED SKINNY JEANS",
      slug: "ripped-skinny-jeans",
      category: "Pants",
      image: "../images/ripped-slim-fit-jeans.jpg",
      price: 259,
      countInStock: 10,
      brand: "ZARA",
      rating: 4,
      numReviews: 3,
      description: "Skinny fit jeans. Five pockets. Faded and ripped effect on the legs. Front zip fly and button fastening.",
    },
    {
      name: "UTILITY CARGO JEANS",
      slug: "utility-cargo-jeans",
      category: "Pants",
      image: "../images/utility-cargo-jeans.jpg",
      price: 379,
      countInStock: 4,
      brand: "ZARA",
      rating: 2,
      numReviews: 3,
      description: "Straight fit jeans. Front pockets and rear patch pockets. Patch pockets with flaps on the legs. Faded effect. Adjustable hem with tab. Front zip fly and button fastening.",
    },
    {
      name: "RIPPED SLIM FIT JEANS",
      slug: "defacto-regular-fit-cargo-pocket-detail-woven-trousers",
      category: "Pants",
      image: "../images/ripped-slim-fit-jeans.jpg",
      price: 259,
      countInStock: 7,
      brand: "ZARA",
      rating: 1,
      numReviews: 1,
      description: "Whitewashed slim fit jeans featuring a five-pocket design and rips with inner patches on the legs. Zip fly and top button",
    },
    {
      name: "BAGGY FIT JEANS",
      slug: "baggy-fit-jeans",
      category: "Pants",
      image: "../images/baggy-fit-jeans.jpg",
      price: 199,
      countInStock: 7,
      brand: "ZARA",
      rating: 4,
      numReviews: 7,
      description: "Baggy fit jeans with a five-pocket design. Front zip fly and top button fastening.",
    },
    {
      name: "MULTIPIECE SNEAKERS",
      slug: "multipiece-sneakers",
      category: "Shoes",
      image: "../images/multipiece-sneakers.jpg",
      price: 329,
      countInStock: 8,
      brand: "ZARA",
      rating: 5,
      numReviews: 3,
      description: "Lace-up trainers. Combination of pieces and colours on the upper. Six-eyelet facing. Contrast-coloured topstitching detail. Slightly chunky sole.",
    },
    {
      name: "MINIMALIST RETRO TRAINERS",
      slug: "minimalist-retro-trainers",
      category: "Shoes",
      image: "../images/minimalist-retro-trainers.jpg",
      price: 179,
      countInStock: 0,
      brand: "ZARA",
      rating: 4.5,
      numReviews: 10,
      description: "Trainers. Monochrome upper with a combination of pieces. Seven-eyelet facing. Uneven chunky sole. Retro-inspired design.",
    },
    {
      name: "CHUNKY TRAINERS",
      slug: "chunky-trainers",
      category: "Shoes",
      image: "../images/chunky-trainers.jpg",
      price: 259,
      countInStock: 10,
      brand: "ZARA",
      rating: 4.5,
      numReviews: 10,
      description: "Trainers with contrast materials and colours on the upper. Seven-eyelet facing. Contrast colour piece at the back. Chunky sole with irregular design.",
    },
    {
      name: "SOCKS WITH ©TONY ALVA GRAPHIC",
      slug: "socks-with--tony-alva-graphic",
      category: "Socks",
      image: "../images/socks-with--tony-alva-graphic.jpg",
      price: 49.9,
      countInStock: 5,
      brand: "ZARA",
      rating: 5,
      numReviews: 3,
      description: "Socks made of a spun cotton blend. © Tony Alva graphic detail. Ribbed trims.",
    },
    {
      name: "POPEYE © KING FEATURES SOCKS",
      slug: "popeye---king-features-socks",
      category: "Socks",
      image: "../images/popeye---king-features-socks.jpg",
      price: 49.9,
      countInStock: 3,
      brand: "ZARA",
      rating: 4.5,
      numReviews: 5,
      description: "Trainers. Monochrome upper with a combination of pieces. Seven-eyelet facing. Uneven chunky sole. Retro-inspired design.",
    },
    {
      name: "PACK OF 3 STRIPED SOCKS",
      slug: "pack-of-3-striped-socks",
      category: "Socks",
      image: "../images/pack-of-3-striped-socks.jpg",
      price: 69.9,
      countInStock: 10,
      brand: "ZARA",
      rating: 4.5,
      numReviews: 10,
      description: "Ribbed knit socks with ribbed elastic trims. Contrast stripe detail.",
    },
  ],
};

export default data;
